### ISSUE TITLE
Role cards

### ISSUE THREAD

**Issue by MittensFFA** [FFA-For-All/Secret-Hitler-Bot#5]
Liberal
Fascist
Hitler

**Comment by MittensFFA** [comment]
Liberal
Fascist
Hitler

**Comment by MittensFFA** [comment]
![Liberal_Role](https://user-images.githubusercontent.com/44099251/70658400-8809d400-1c23-11ea-9e10-22801a37c7c2.png)
![Liberal_Party](https://user-images.githubusercontent.com/44099251/70657679-dfa74000-1c21-11ea-8cd2-44756a4f1229.png)
![Fascist_Role](https://user-images.githubusercontent.com/44099251/70657689-e7ff7b00-1c21-11ea-9555-1e69771d1dfa.png)
![Hitler_Role](https://user-images.githubusercontent.com/44099251/70657694-eafa6b80-1c21-11ea-87e1-ed56765bbbae.png)
![Fascist_Party](https://user-images.githubusercontent.com/44099251/70658410-8d671e80-1c23-11ea-935c-e7a7b9a3d2d5.png)

**Comment by orderbs** [comment]
Ideally, these would all be in the repo somewhere.

I can submit a PR.
