### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by MittensFFA** [FFA-For-All/Secret-Hitler-Bot#6]
Liberal article
Fascist article

**Comment by MittensFFA** [comment]
![Liberal_Article_zpsropgspl5](https://user-images.githubusercontent.com/44099251/70657916-71af4880-1c22-11ea-9cb9-956f9bc97e5b.png)
![Fascist_Article_zps36fxlbdg](https://user-images.githubusercontent.com/44099251/70657922-7673fc80-1c22-11ea-89b3-daae1d2fb66f.png)

**Comment by orderbs** [comment]
These should be added to /images

I can submit a PR.
